---
- name: check from devices operationnal state if desirated vlans are presents on QFX10k
  hosts: QFX10k
  connection: local
  gather_facts: no  
  tasks:
  - name: check vlans
    junos_command:
      provider: "{{ credentials }}"
      commands:
       - show vlans {{ item.name }}
      waitfor:
       - "result[0]['l2ng-l2ald-vlan-instance-information']['l2ng-l2ald-vlan-instance-group']['l2ng-l2rtb-vlan-name'] eq {{ item.name }}"
    with_items: "{{ vlanlist }}"

- name: check from devices operationnal state if desirated vlans are presents on QFX5k
  hosts: QFX5k
  connection: local
  gather_facts: no
  tasks:
  - name: check vlans
    junos_command:
      provider: "{{ credentials }}"
      commands:
       - show vlans {{ item.name }}
      waitfor:
       - "result[0].vlan-information.vlan.vlan-name eq {{item.name }}"
    with_items: "{{ vlanlist }}"
 


